root: true
env:
  browser: true
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  # When Using TypeScript, Setting of Root Dir. ( To Find for tsconfig.json )
  tsconfigRootDir: "."
  # When Using TypeScript, Import tsconfig Setting.
  project: "./tsconfig.json"
  sourceType: module
  ecmaFeatures:
    jsx: true
  extraFileExtensions: ".vue"
plugins:
  - react
  - react-hooks
  - prettier
  - import
  - "@typescript-eslint"
settings:
  # Import webpack Alias Setting, Linting for 'import/no-unresolved'.
  # If Using JavaScript FrameWork or Library. -> webpack/webpack.base.babel.js
  # If Create Static Website. -> webpack/webpack.gulp.base.babel.js
  "import/resolver":
    webpack:
      config: "webpack/webpack.base.babel.js"
  react:
    version: "detect"
  node:
    tryExtensions:
      - ".js"
      - ".ts"
      - ".jsx"
      - ".tsx"
      - ".vue"
      - ".json"
      - ".node"
#
#
# Set Linting Rules Below.
extends:
  - "standard"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  "prettier/prettier":
    - error
    - tabWidth: 2
      trailingComma: none
      singleQuote: true
      semi: false
      printWidth: 160
  indent: off
  "@typescript-eslint/indent":
    - error
    - 2
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/member-delimiter-style": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/prefer-interface": off
  "max-classes-per-file":
    - error
    - 2
  "no-bitwise":
    - error
    - allow:
        - "~"
  "import/order": off
  "sort-keys": off
  "no-multiple-empty-lines": off
  "lines-between-class-members":
    - error
    - always
    - exceptAfterSingleLine: true
  "no-console": off
  "unicorn/number-literal-case": off
  "spaced-comment":
    - error
    - always
  "react/prop-types": off
  "react-hooks/rules-of-hooks": error
  "react-hooks/exhaustive-deps": warn
  # "@typescript-eslint/ban-ts-ignore": off